name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check fmt
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy --examples
      - name: Run (addition)
        run: cargo run --example addition
      - name: Run (mnist)
        run: cargo run --example mnist
      - name: Run (regression_savedmodel)
        run: cargo run --example regression_savedmodel
      - name: Run (regression_checkpoint)
        run: cargo run --example regression_checkpoint
      - name: Run (mnist_savedmodel)
        run: cargo run --example mnist_savedmodel
      - name: Run (zenn)
        run: cargo run --example zenn
